### ISSUE TITLE
Dynamically configure service or ingress

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/mononoke#11]
**Floating the idea not a priority**

**What problem are we solving?**
Inbound network traffic to the pod will be configured differently depending on what type of cluster is running. Don't make me think about confusing concepts just do the right thing whilst allowing me to override the behaviour 

* Chose a LoadBalancer service if available.
* Otherwise use an Ingress resource
* Use a NodePort as last resort

**Comment by scothis** [comment]
We should defer to users to define an appropriate Service if/when needed. There's a reason why Deployment doesn't automatically create a Service.

One thing I don't like about our current behavior of creating a Deployment (it's there for expediancy) is that it creates a Deployment. We should be flexible enough encode our knowledge of how to run a Spring Boot container, that it shouldn't matter what lifecycle semantics are used to run the container (Deployment, Job, DaemonSet, Knative Service, YetToBeDefinedThinger, etc). As long as the target defines a PodTemplateSpec, we should be able to inject the boot container.

The cases were we should create a Service is for internal observability (e.g. Prometheus)

**Comment by ojhughes** [comment]
Sure and actually from a user PoV skaffold makes this so simple anyway because it handles port forwarding automatically
