### ISSUE TITLE
Opinion on SIGTERM handling

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/mononoke#13]
see https://github.com/spring-projects/spring-boot/issues/4657

we could handle this using an opinionated workaround

**Comment by scothis** [comment]
Is the opinion to set `server.shutdown.grace-period` to something like 90% of `terminationGracePeriodSeconds`?

**Comment by ojhughes** [comment]
@scothis yes that is a sensible starting point although it means we will need to track Boot 2.3.BUILD-SNAPSHOT

**Comment by scothis** [comment]
What's the harm if we set the property on an older version of boot? We can do a semver check if needed

**Comment by ojhughes** [comment]
Looks like the property only exists in a recent commit https://github.com/spring-projects/spring-boot/commit/308e1d36759db12f3e49fa158514e6d0c8fd66ed

No harm in setting it on an old version but we might want to do something else instead

**Comment by scothis** [comment]
Resolved by #27
