### ISSUE TITLE
Add missing dependencies to a Spring Boot Application

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/mononoke#15]
**Stretch goal**
If the `spring-boot-actuator-starter` is missing, we should optionally add it during build.

This pattern could be used in other places, especially if we need to provide client connectors like [we do currently in SCS](https://github.com/pivotal-cf/spring-cloud-services-connector)

**Comment by ojhughes** [comment]
cc @ekcasey

**Comment by ekcasey** [comment]
@ojhughes Are you suggesting this as a spring-boot-cnb feature?

**Comment by ojhughes** [comment]
@ekcasey I thought this might be just a custom builder? Just so we can add in the extra dependency

**Comment by ojhughes** [comment]
Alternatively, a container volume containing the desired classpath entries could be mounted with container, with the `java -cp ...` argument appended. This is easier to reason about I think

**Comment by ojhughes** [comment]
Closing following discussions on scope of spike
