### ISSUE TITLE
Enable debug port for a Spring Boot

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/mononoke#20]
**Stretch goal**
Enable a running Pod to be patched to set the JVM argument for remote debugging 
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005` and expose port 5005 from the container

**Comment by scothis** [comment]
I wonder if we can use something cross cutting, like [Squash](https://squash.solo.io)?

**Comment by ojhughes** [comment]
Squash looks ideal actually
